name: test app

on:
  push:
    # branches:
    #   - phapawith/20240501_branch
    # paths-ignore:
    #   - '.github/workflows/*'
    #   - app.py
  pull_request:
    types:
      - synchronize
      - opened
  workflow_dispatch:

env:
  WORKFLOW_ENV: "this is workflow env....."


jobs:
  test:
    environment: testing
    env:
      FROM_ENVIRONMENT_GITHUB_ACTION_2: ${{ vars.FROM_ENVIRONMENT_GITHUB_ACTION_2 }}
      FROM_ENVIRONMENT_GITHUB_ACTION: ${{ vars.FROM_ENVIRONMENT_GITHUB_ACTION }}
      ENV_FROM_JOB: "Jobs env..."
    runs-on: ubuntu-latest

    steps:
      - name: get code from github
        uses: actions/checkout@v4

      - name: setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.2'
              
      - name: run python script
        run: |
          python3 test.py


    