name: test app

on:
  push:
    # branches:
    #   - phapawith/20240501_branch
    # paths-ignore:
    #   - '.github/workflows/*'
    #   - app.py
  pull_request:
    types:
      - synchronize
      - opened

env:
  WORKFLOW_ENV: "this is workflow env....."


jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    env:
      ENV_FROM_JOB: "Jobs env..."

    steps:
      - name: get code from github
        uses: actions/checkout@v4

      - name: setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.2' 
              
      - name: run python script
        run: |
          python3 test.py


    